
spring:
  mail:
    host: smtp.gmail.com
    username: youremail@gmail.com
    password: app passwords
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
server:
  port: 9090